# Generated by Django 3.1.6 on 2021-05-29 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_password', models.CharField(max_length=32)),
                ('user_name', models.CharField(max_length=25)),
                ('user_phone', models.CharField(max_length=15)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_role', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grad.user')),
            ],
            bases=('grad.user',),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grad.user')),
            ],
            bases=('grad.user',),
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grad.user')),
                ('specialist_brief', models.CharField(max_length=500)),
                ('specialist_active_status', models.BooleanField()),
            ],
            bases=('grad.user',),
        ),
        migrations.CreateModel(
            name='VideoSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_price', models.FloatField()),
                ('video_duration_in_minutes', models.IntegerField()),
                ('video_date', models.DateField()),
                ('video_start_time', models.TimeField()),
                ('video_end_time', models.TimeField()),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VideoSessions', to='grad.parent')),
                ('specialist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VideoSessions', to='grad.specialist')),
            ],
        ),
        migrations.CreateModel(
            name='SingleInquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_price', models.FloatField()),
                ('inquire_duration_in_minutes', models.IntegerField()),
                ('inquiry_start_time', models.TimeField()),
                ('inquiry_end_time', models.TimeField()),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Chats', to='grad.parent')),
                ('specialist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Chats', to='grad.specialist')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_body', models.CharField(max_length=1000)),
                ('question_date', models.DateTimeField()),
                ('question_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grad.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_body', models.CharField(max_length=1000)),
                ('answer_date', models.DateTimeField()),
                ('answer_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grad.question')),
                ('answer_specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnsweredQuestions', to='grad.specialist')),
            ],
        ),
    ]
