# Generated by Django 3.1.6 on 2021-06-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_tags',
            field=models.CharField(default='', max_length=200),
        ),
    ]
