# Generated by Django 3.1.6 on 2021-06-01 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grad', '0002_question_question_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_day', models.CharField(max_length=20)),
                ('free_day_start_time', models.TimeField()),
                ('free_day_end_time', models.TimeField()),
                ('schedule_specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grad.specialist')),
            ],
        ),
    ]
