name: parenting_specialist
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  watson_assistant_v2: ^0.0.1
  cupertino_icons: ^0.1.2
  bubble: ^1.2.1
  backendless_sdk: ^6.3.0
  flutter_svg: ^0.19.1
  provider: ^4.3.1
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  fluttertoast: ^8.0.7
  agora_rtc_engine: ^3.3.3
  permission_handler: ^5.0.1
  intl: ^0.17.0
  # flutter_datetime_picker: ^1.5.1
  http: ^0.12.1
  crypto: ^2.1.5
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master
  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
   - assets/images/Specialist.png
   - assets/images/User.png
   - assets/images/MumBot3.png
   - assets/images/Video.jpg
   - assets/images/Chat.png
   - assets/images/waiting.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
